name: Build
on:
    push:
        branches:
            - main
        paths-ignore:
            - '*.md'
            - '*.puml'
            - '.github/workflows/release.yaml'
    pull_request:
        branches:
            - main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
            GOLANGCI_LINT_VERSION: v1.57.2
            YAEGI_VERSION: v0.14.3
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 10
            -   uses: wagoid/commitlint-github-action@v6
            -   uses: actions/setup-go@v5
                with:
                    go-version-file: ${{ github.workspace }}/go.mod
            -   uses: golangci/golangci-lint-action@v6
                with:
                    version: ${{ env.GOLANGCI_LINT_VERSION }}
                    args: "--help"
            -   name: setup yaegi
                run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b /home/runner/.local/bin ${YAEGI_VERSION}
            -   name: test
                run: make test
